-- Merge curated Atlanta data (curated wins over OSM duplicates)
begin;

update cities set name_ar='أتلانتا', name_es='Atlanta' where id='atlanta';

-- Drop OSM rows duplicated by a curated entry
delete from locations where source='osm' and city_id='atlanta' and lat between 33.688049 and 33.690751 and lng between -84.347224 and -84.343976;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.784949 and 33.787651 and lng between -84.404726 and -84.401474;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.807849 and 33.810551 and lng between -84.423326 and -84.420074;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.572549 and 33.575251 and lng between -84.471222 and -84.467978;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.690749 and 33.693451 and lng between -84.353924 and -84.350676;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.884049 and 33.886751 and lng between -84.345928 and -84.342672;
delete from locations where source='osm' and city_id='atlanta' and lat between 34.045349 and 34.048051 and lng between -84.278531 and -84.275269;
delete from locations where source='osm' and city_id='atlanta' and lat between 34.041449 and 34.044151 and lng between -84.376531 and -84.373269;
delete from locations where source='osm' and city_id='atlanta' and lat between 34.049249 and 34.051951 and lng between -84.285831 and -84.282569;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.944049 and 33.946751 and lng between -84.509129 and -84.505871;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.945349 and 33.948051 and lng between -84.524729 and -84.521471;
delete from locations where source='osm' and city_id='atlanta' and lat between 34.023549 and 34.026251 and lng between -84.614831 and -84.611569;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.628449 and 33.631151 and lng between -84.379923 and -84.376677;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.648249 and 33.650951 and lng between -84.006523 and -84.003277;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.755949 and 33.758651 and lng between -84.392625 and -84.389375;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.852649 and 33.855351 and lng between -84.308127 and -84.304873;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.812649 and 33.815351 and lng between -84.336826 and -84.333574;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.972849 and 33.975551 and lng between -84.306730 and -84.303470;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.735449 and 33.738151 and lng between -84.417525 and -84.414275;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.889249 and 33.891951 and lng between -84.345528 and -84.342272;
delete from locations where source='osm' and city_id='atlanta' and lat between 34.045849 and 34.048551 and lng between -84.270531 and -84.267269;
delete from locations where source='osm' and city_id='atlanta' and lat between 34.055749 and 34.058451 and lng between -84.181231 and -84.177969;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.967649 and 33.970351 and lng between -84.546429 and -84.543171;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.497749 and 33.500451 and lng between -84.363221 and -84.359979;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.952249 and 33.954951 and lng between -84.551929 and -84.548671;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.703549 and 33.706251 and lng between -84.464024 and -84.460776;
delete from locations where source='osm' and city_id='atlanta' and lat between 34.053049 and 34.055751 and lng between -84.343731 and -84.340469;
delete from locations where source='osm' and city_id='atlanta' and lat between 34.047249 and 34.049951 and lng between -84.293931 and -84.290669;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.835849 and 33.838551 and lng between -84.316027 and -84.312773;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.972949 and 33.975651 and lng between -84.306830 and -84.303570;
delete from locations where source='osm' and city_id='atlanta' and lat between 34.005249 and 34.007951 and lng between -84.533530 and -84.530270;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.936049 and 33.938751 and lng between -84.175529 and -84.172271;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.784749 and 33.787451 and lng between -84.375626 and -84.372374;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.757649 and 33.760351 and lng between -84.394925 and -84.391675;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.789149 and 33.791851 and lng between -84.374426 and -84.371174;
delete from locations where source='osm' and city_id='atlanta' and lat between 34.008749 and 34.011451 and lng between -84.397630 and -84.394370;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.804749 and 33.807451 and lng between -84.149126 and -84.145874;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.661049 and 33.663751 and lng between -84.112524 and -84.109276;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.784249 and 33.786951 and lng between -84.385726 and -84.382474;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.761149 and 33.763851 and lng between -84.395825 and -84.392575;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.761949 and 33.764651 and lng between -84.394626 and -84.391374;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.792049 and 33.794751 and lng between -84.389526 and -84.386274;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.651249 and 33.653951 and lng between -84.428223 and -84.424977;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.808049 and 33.810751 and lng between -84.437326 and -84.434074;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.783549 and 33.786251 and lng between -84.416026 and -84.412774;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.810949 and 33.813651 and lng between -84.441726 and -84.438474;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.719049 and 33.721751 and lng between -84.349125 and -84.345875;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.876149 and 33.878851 and lng between -84.468428 and -84.465172;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.919249 and 33.921951 and lng between -84.341129 and -84.337871;
delete from locations where source='osm' and city_id='atlanta' and lat between 33.754049 and 33.756751 and lng between -84.402625 and -84.399375;

-- Upsert curated locations
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', 'Atlanta Masjid of Al-Islam', 'مسجد أتلانتا', 'Mezquita Atlanta de Al-Islam', '560 Fayetteville Rd SE, Atlanta, GA 30316', 33.6894, -84.3456, '+14043780011', 'Jumu''ah 1:00 PM', 'الجمعة ١:٠٠ م', 'Yumu''ah 1:00 PM', false, true, true, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/atlanta-masjid-of-al-islam')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', 'Masjid Al-Farooq', 'مسجد الفاروق', 'Mezquita Al-Farooq', '442 14th St NW, Atlanta, GA 30318', 33.7863, -84.4031, '+14048761111', 'Jumu''ah 1:00 PM & 2:00 PM', 'الجمعة ١:٠٠ م و ٢:٠٠ م', 'Yumu''ah 1:00 PM y 2:00 PM', false, true, true, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/masjid-al-farooq')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', 'Al-Hedaya Islamic Center', 'المركز الإسلامي الهداية', 'Centro Islámico Al-Hedaya', '1880 Marietta Blvd NW, Atlanta, GA 30318', 33.8092, -84.4217, '+14043552233', 'Jumu''ah 1:15 PM', 'الجمعة ١:١٥ م', 'Yumu''ah 1:15 PM', false, true, true, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/al-hedaya-islamic-center')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', 'Masjid Al-Muminun', 'مسجد المؤمنين', 'Mezquita Al-Muminun', '6096 Old National Hwy, Riverdale, GA 30296', 33.5739, -84.4696, '+17707718867', 'Jumu''ah 1:30 PM', 'الجمعة ١:٣٠ م', 'Yumu''ah 1:30 PM', false, true, true, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/masjid-al-muminun')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', 'Masjid Al-Quran Inc.', 'مسجد القرآن', 'Mezquita Al-Quran', '500 McDonough Blvd SE, Atlanta, GA 30315', 33.6921, -84.3523, '+14046225511', 'Contact masjid', 'اتصل بالمسجد', 'Contactar a la mezquita', false, true, true, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/masjid-al-quran-inc')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', 'King Fahad Mosque', 'مسجد الملك فهد', 'Mezquita Rey Fahd', '4700 Tudor Dr, Atlanta, GA 30342', 33.8854, -84.3443, '+14042570999', 'Jumu''ah 12:30 PM & 1:30 PM', 'الجمعة ١٢:٣٠ م و ١:٣٠ م', 'Yumu''ah 12:30 PM y 1:30 PM', false, true, true, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/king-fahad-mosque')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', 'North Atlanta Masjid', 'مسجد شمال أتلانتا', 'Mezquita del Norte de Atlanta', '10800 Jones Bridge Rd, Alpharetta, GA 30022', 34.0467, -84.2769, '+17703921544', 'Jumu''ah 1:15 PM', 'الجمعة ١:١٥ م', 'Yumu''ah 1:15 PM', false, true, true, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/north-atlanta-masjid')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', 'Masjid Al-Hedayah', 'مسجد الهداية', 'Mezquita Al-Hedayah', '2200 Fowler St, Roswell, GA 30075', 34.0428, -84.3749, '+17707171375', 'Jumu''ah 1:00 PM', 'الجمعة ١:٠٠ م', 'Yumu''ah 1:00 PM', false, true, true, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/masjid-al-hedayah')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', 'Islamic Center of Alpharetta (ICA)', 'المركز الإسلامي لألفاريتا', 'Centro Islámico de Alpharetta', '1200 N Point Dr, Alpharetta, GA 30022', 34.0506, -84.2842, '+16787231613', 'Jumu''ah 1:00 PM (two khutbahs)', 'الجمعة ١:٠٠ م (خطبتان)', 'Yumu''ah 1:00 PM (dos jutbas)', false, true, true, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/islamic-center-of-alpharetta-ica')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', 'Marietta Masjid', 'مسجد مارييتا', 'Mezquita de Marietta', '536 Franklin Gateway SE, Marietta, GA 30067', 33.9454, -84.5075, '+17707882212', 'Jumu''ah 1:00 PM', 'الجمعة ١:٠٠ م', 'Yumu''ah 1:00 PM', false, true, true, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/marietta-masjid')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', 'Al-Farooq Masjid of Marietta', 'مسجد الفاروق – مارييتا', 'Mezquita Al-Farooq de Marietta', '34 S Marietta Pkwy SW, Marietta, GA 30064', 33.9467, -84.5231, '+17707933216', 'Jumu''ah 1:15 PM', 'الجمعة ١:١٥ م', 'Yumu''ah 1:15 PM', false, true, true, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/al-farooq-masjid-of-marietta')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', 'Kennesaw Islamic Center', 'المركز الإسلامي لكينيساو', 'Centro Islámico de Kennesaw', '2828 Summer St, Kennesaw, GA 30144', 34.0249, -84.6132, '+17704490399', 'Jumu''ah 1:30 PM', 'الجمعة ١:٣٠ م', 'Yumu''ah 1:30 PM', false, true, true, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/kennesaw-islamic-center')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', 'Al-Farooq Center (South)', 'مركز الفاروق (الجنوبي)', 'Centro Al-Farooq (Sur)', '3980 Jonesboro Rd, Forest Park, GA 30297', 33.6298, -84.3783, '+14046081474', 'Jumu''ah 1:30 PM', 'الجمعة ١:٣٠ م', 'Yumu''ah 1:30 PM', false, true, true, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/al-farooq-center-south')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', 'Masjid Ash-Shura', 'مسجد الشورى', 'Mezquita Ash-Shura', '1580 Eastside Dr, Conyers, GA 30013', 33.6496, -84.0049, '+17704830997', 'Jumu''ah 1:00 PM', 'الجمعة ١:٠٠ م', 'Yumu''ah 1:00 PM', false, true, true, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/masjid-ash-shura')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'Baraka Shawarma', 'باراكا شاورما', 'Baraka Shawarma', '68 Walton St NW, Atlanta, GA 30303', 33.7573, -84.391, '+14046002004', 'Mon-Thu 11AM-11PM, Fri-Sat 11AM-3AM, Sun 12PM-11PM', 'الإثنين-الخميس ١١ص-١١م، الجمعة-السبت ١١ص-٣ص، الأحد ١٢م-١١م', 'Lun-Jue 11-23h, Vie-Sáb 11-3h, Dom 12-23h', true, true, true, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/baraka-shawarma')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'Bismillah Cafe', 'بسملة كافيه', 'Bismillah Café', '4022 Buford Hwy NE, Atlanta, GA 30345', 33.854, -84.3065, '+17703654244', 'Daily 11AM-10PM', 'يومياً ١١ص-١٠م', 'Todos los días 11-22h', true, true, true, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/bismillah-cafe')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'Che Butter Jonez', 'تشي بتر جونز', 'Che Butter Jonez', '1602 Lavista Rd NE, Atlanta, GA 30329', 33.814, -84.3352, '+14049665883', 'Wed-Thu 11AM-7PM, Fri-Sat 12PM-8PM, Closed Mon-Tue', 'الأربعاء-الخميس ١١ص-٧م، الجمعة-السبت ١٢م-٨م', 'Mié-Jue 11-19h, Vie-Sáb 12-20h, Cerrado Lun-Mar', false, false, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/che-butter-jonez')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'Aamar''s Indian Cuisine', 'عامر الهندي', 'Cocina India de Aamar', '2090 Dunwoody Club Dr, Sandy Springs, GA 30350', 33.9742, -84.3051, '+17708280004', 'Daily 11:30AM-9:30PM', 'يومياً ١١:٣٠ص-٩:٣٠م', 'Todos los días 11:30-21:30h', true, true, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/aamars-indian-cuisine')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'Tassili''s Raw Reality', 'تاسيلي ريريتي', 'Tassili''s Raw Reality', '1059 Ralph David Abernathy Blvd SW, Atlanta, GA 30310', 33.7368, -84.4159, '+14045485750', 'Tue-Sat 11AM-7PM, Sun 1PM-5PM', 'الثلاثاء-السبت ١١ص-٧م، الأحد ١م-٥م', 'Mar-Sáb 11-19h, Dom 13-17h', true, true, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/tassilis-raw-reality')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'Cafe Agora', 'كافيه أغورا', 'Café Agora', '2002 Summit Blvd, Sandy Springs, GA 30319', 33.8906, -84.3439, '+14043201424', 'Sun-Thu 11AM-9PM, Fri-Sat 11AM-10PM', 'الأحد-الخميس ١١ص-٩م، الجمعة-السبت ١١ص-١٠م', 'Dom-Jue 11-21h, Vie-Sáb 11-22h', true, true, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/cafe-agora')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'Masti', 'ماستي', 'Masti', '3000 Old Alabama Rd, Alpharetta, GA 30022', 34.0472, -84.2689, '+17704677733', 'Daily 11AM-10PM', 'يومياً ١١ص-١٠م', 'Todos los días 11-22h', true, true, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/masti')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'Hot Cafe', 'هوت كافيه', 'Hot Café', '11030 Medlock Bridge Rd, Johns Creek, GA 30097', 34.0571, -84.1796, '+16782616506', 'Daily 11AM-9PM', 'يومياً ١١ص-٩م', 'Todos los días 11-21h', true, true, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/hot-cafe')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'Falafel Cafe', 'فلافل كافيه', 'Falafel Café', '950 Cobb Pkwy, Marietta, GA 30062', 33.969, -84.5448, '+17704290002', 'Tue-Sun 11AM-9PM', 'الثلاثاء-الأحد ١١ص-٩م', 'Mar-Dom 11-21h', true, true, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/falafel-cafe')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'Madina Restaurant', 'مطعم المدينة', 'Restaurante Madina', '1451 Washington Rd, Jonesboro, GA 30236', 33.4991, -84.3616, '+17706025455', 'Daily 10AM-10PM', 'يومياً ١٠ص-١٠م', 'Todos los días 10-22h', true, true, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/madina-restaurant')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'coffee', 'Chai & Co.', 'تشاي آند كو', 'Chai & Co.', '63 Atlanta St, Marietta, GA 30060', 33.9536, -84.5503, '+17704351234', 'Daily 8AM-8PM, Ramadan extended', 'يومياً ٨ص-٨م، رمضان حتى وقت متأخر', 'Todos los días 8-20h, horario ampliado en Ramadán', true, true, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/chai-co')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'coffee', 'Land of a Thousand Hills', 'لاند أوف أ ثاوزند هيلز', 'Land of a Thousand Hills', '2465 Cascade Rd SW, Atlanta, GA 30311', 33.7049, -84.4624, '+14047666407', 'Mon-Sat 7AM-6PM, Sun 8AM-5PM', 'الإثنين-السبت ٧ص-٦م، الأحد ٨ص-٥م', 'Lun-Sáb 7-18h, Dom 8-17h', false, true, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/land-of-a-thousand-hills')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'garments', 'Zawadi', 'زوادي', 'Zawadi', '10800 Alpharetta Hwy, Roswell, GA 30076', 34.0544, -84.3421, '+16786394267', 'Mon-Sat 10AM-7PM, Sun 12PM-5PM', 'الإثنين-السبت ١٠ص-٧م، الأحد ١٢م-٥م', 'Lun-Sáb 10-19h, Dom 12-17h', false, true, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/zawadi')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'garments', 'Al-Jannat Collection', 'مجموعة الجَنات', 'Colección Al-Jannat', '6000 N Point Pkwy, Alpharetta, GA 30022', 34.0486, -84.2923, '+16785362222', 'Mon-Sat 10AM-8PM, Sun 12PM-6PM', 'الإثنين-السبت ١٠ص-٨م، الأحد ١٢م-٦م', 'Lun-Sáb 10-20h, Dom 12-18h', false, true, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/al-jannat-collection')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'garments', 'House of Deen', 'هاوس أوف دين', 'House of Deen', '2779 Clairmont Rd NE, Atlanta, GA 30329', 33.8372, -84.3144, '+14046397681', 'Tue-Sat 11AM-7PM', 'الثلاثاء-السبت ١١ص-٧م', 'Mar-Sáb 11-19h', false, true, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/house-of-deen')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'grocery', 'Bazaar International Market', 'بازار إنترناشونال ماركت', 'Mercado Internacional Bazaar', '2090 Dunwoody Club Dr, Sandy Springs, GA 30350', 33.9743, -84.3052, '+17708280002', 'Daily 9AM-10PM', 'يومياً ٩ص-١٠م', 'Todos los días 9-22h', true, true, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/bazaar-international-market')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'grocery', 'Jerusalem Market', 'سوق القدس', 'Mercado Jerusalén', '1463 Canton Rd, Marietta, GA 30066', 34.0066, -84.5319, '+16782024447', 'Daily 9AM-9PM', 'يومياً ٩ص-٩م', 'Todos los días 9-21h', true, true, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/jerusalem-market')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'grocery', 'Sabri Mart', 'سابري مارت', 'Sabri Mart', '1215 Indian Trail Rd, Norcross, GA 30093', 33.9374, -84.1739, '+16784529377', 'Daily 8AM-10PM', 'يومياً ٨ص-١٠م', 'Todos los días 8-22h', true, true, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/sabri-mart')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'park', 'Piedmont Park', 'متنزه بيدمونت', 'Parque Piedmont', '400 Park Dr NE, Atlanta, GA 30306', 33.7861, -84.374, '+14048752575', '6AM-11PM daily', '٦ص-١١م يومياً', '6-23h todos los días', false, true, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/piedmont-park')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'park', 'Centennial Olympic Park', 'منتزه سنتينيال الأولمبي', 'Parque Olímpico del Centenario', '265 Park Ave W NW, Atlanta, GA 30313', 33.759, -84.3933, '+14042234419', '7AM-9PM daily', '٧ص-٩م يومياً', '7-21h todos los días', false, false, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/centennial-olympic-park')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'museum', 'Atlanta Botanical Garden', 'حديقة أتلانتا النباتية', 'Jardín Botánico de Atlanta', '1345 Piedmont Ave NE, Atlanta, GA 30309', 33.7905, -84.3728, '+14048765859', 'Daily 9AM-9PM (seasonal)', 'يومياً ٩ص-٩م (حسب الموسم)', 'Todos los días 9-21h (según temporada)', false, true, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/atlanta-botanical-garden')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'park', 'Chattahoochee Nature Center', 'مركز شاتاهوتشي الطبيعي', 'Centro de Naturaleza Chattahoochee', '9135 Willeo Rd, Roswell, GA 30075', 34.0101, -84.396, '+17709926220', 'Mon-Sat 9AM-5PM, Sun 12PM-5PM', 'الإثنين-السبت ٩ص-٥م، الأحد ١٢م-٥م', 'Lun-Sáb 9-17h, Dom 12-17h', false, true, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/chattahoochee-nature-center')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'attraction', 'Stone Mountain Park', 'منتزه ستون ماونتن', 'Parque Stone Mountain', '1000 Robert E Lee Blvd, Stone Mountain, GA 30083', 33.8061, -84.1475, '+18004012407', '5AM-12AM daily', '٥ص-١٢ص يومياً', '5-24h todos los días', false, false, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/stone-mountain-park')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'park', 'Arabia Mountain National Heritage Area', 'منطقة أرابيا ماونتن التراثية', 'Área Patrimonial Arabia Mountain', '3787 Klondike Rd, Stonecrest, GA 30038', 33.6624, -84.1109, '+17704841880', 'Dawn to dusk', 'من الفجر حتى الغسق', 'Del amanecer al anochecer', false, true, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/arabia-mountain-national-heritage-area')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'museum', 'High Museum of Art', 'متحف هاي للفنون', 'Museo de Arte High', '1280 Peachtree St NE, Atlanta, GA 30309', 33.7856, -84.3841, '+14047334400', 'Mon-Sat 10AM-5PM, Sun 12PM-5PM', 'الإثنين-السبت ١٠ص-٥م، الأحد ١٢م-٥م', 'Lun-Sáb 10-17h, Dom 12-17h', false, false, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/high-museum-of-art')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'museum', 'Georgia Aquarium', 'حوض أتلانتا المائي', 'Acuario de Georgia', '225 Baker St NW, Atlanta, GA 30313', 33.7625, -84.3942, '+14045813600', 'Daily 9AM-6PM', 'يومياً ٩ص-٦م', 'Todos los días 9-18h', false, false, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/georgia-aquarium')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'museum', 'World of Coca-Cola', 'عالم كوكا كولا', 'Mundo de Coca-Cola', '121 Baker St NW, Atlanta, GA 30313', 33.7633, -84.393, '+14046765151', 'Daily 10AM-5PM', 'يومياً ١٠ص-٥م', 'Todos los días 10-17h', false, true, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/world-of-coca-cola')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'attraction', 'Center for Puppetry Arts', 'مركز فنون الدمى', 'Centro de Arte de Marionetas', '1404 Spring St NW, Atlanta, GA 30309', 33.7934, -84.3879, '+14048733389', 'Tue-Sat 9AM-5PM, Sun 11AM-5PM', 'الثلاثاء-السبت ٩ص-٥م، الأحد ١١ص-٥م', 'Mar-Sáb 9-17h, Dom 11-17h', false, true, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/center-for-puppetry-arts')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'attraction', 'Delta Flight Museum', 'متحف دلتا للطيران', 'Museo de Aviación Delta', '1060 Delta Blvd, Atlanta, GA 30354', 33.6526, -84.4266, '+14047153222', 'Daily 10AM-4PM', 'يومياً ١٠ص-٤م', 'Todos los días 10-16h', false, true, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/delta-flight-museum')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'attraction', 'Beat the Bomb', 'بيت ذا بومب', 'Beat the Bomb', '1483 Chattahoochee Ave NW, Atlanta, GA 30318', 33.8094, -84.4357, '+14044662400', 'Daily 10AM-10PM', 'يومياً ١٠ص-١٠م', 'Todos los días 10-22h', false, true, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/beat-the-bomb')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'attraction', 'Escape Game Atlanta', 'إسكيب غيم أتلانتا', 'Escape Game Atlanta', '1115 Howell Mill Rd NW, Atlanta, GA 30318', 33.7849, -84.4144, '+14044937252', 'Daily 9AM-12AM', 'يومياً ٩ص-١٢ص', 'Todos los días 9-24h', false, true, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/escape-game-atlanta')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'attraction', 'Your 3rd Spot', 'يور ثيرد سبوت', 'Your 3rd Spot', '400 Chattahoochee Row NW, Atlanta, GA 30318', 33.8123, -84.4401, '+14047085555', 'Daily 11AM-12AM', 'يومياً ١١ص-١٢ص', 'Todos los días 11-24h', false, false, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/your-3rd-spot')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'attraction', 'Starlight Drive-In', 'ستارلايت درايف إن', 'Autocine Starlight', '2000 Moreland Ave SE, Atlanta, GA 30316', 33.7204, -84.3475, '+14046275709', 'Fri-Sun 7PM-12AM', 'الجمعة-الأحد ٧م-١٢ص', 'Vie-Dom 19-24h', false, true, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/starlight-drive-in')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'mall', 'Cumberland Mall', 'كمبرلاند مول', 'Centro Comercial Cumberland', '1000 Cumberland Mall, Atlanta, GA 30339', 33.8775, -84.4668, '+17704359741', 'Mon-Sat 10AM-9PM, Sun 12PM-6PM', 'الإثنين-السبت ١٠ص-٩م، الأحد ١٢م-٦م', 'Lun-Sáb 10-21h, Dom 12-18h', false, true, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/cumberland-mall')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'mall', 'Perimeter Mall', 'بيرميتر مول', 'Centro Comercial Perimeter', '4400 Ashford Dunwoody Rd, Dunwoody, GA 30346', 33.9206, -84.3395, '+16784343888', 'Mon-Sat 10AM-9PM, Sun 11AM-6PM', 'الإثنين-السبت ١٠ص-٩م، الأحد ١١ص-٦م', 'Lun-Sáb 10-21h, Dom 11-18h', false, true, false, true, false, NULL, NULL, NULL, NULL, 'curated', 'curated/perimeter-mall')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'worldcup_venue', 'Mercedes-Benz Stadium', 'ملعب مرسيدس بنز', 'Estadio Mercedes-Benz', '1414 Andrew Young International Blvd NW, Atlanta, GA 30313', 33.7554, -84.401, '+14042224200', 'Match days only – wudu at Gate 1/4, prayer room Gate 2 Level 100, halal food Sections 120 & 210', 'أيام المباريات فقط – الوضوء البوابة ١ و٤، غرفة الصلاة البوابة ٢ الطابق ١٠٠، طعام حلال القسم ١٢٠ و٢١٠', 'Solo días de partido – wudu en Puerta 1/4, sala de oración Puerta 2 Nivel 100, comida halal Secciones 120 y 210', true, false, true, false, true, 'GREENATL2026', '10% off merch at the stadium store', 'خصم ١٠٪ على البضائع في متجر الملعب', '10% de descuento en productos en la tienda del estadio', 'curated', 'curated/mercedes-benz-stadium')
on conflict (osm_id) do update set name_en=excluded.name_en, name_ar=excluded.name_ar, name_es=excluded.name_es, address=excluded.address, hours_en=excluded.hours_en, hours_ar=excluded.hours_ar, hours_es=excluded.hours_es, phone=excluded.phone, halal_certified=excluded.halal_certified, alcohol_free=excluded.alcohol_free, prayer_space=excluded.prayer_space, family_friendly=excluded.family_friendly, worldcup_special=excluded.worldcup_special, discount_code=excluded.discount_code, discount_offer_en=excluded.discount_offer_en, discount_offer_ar=excluded.discount_offer_ar, discount_offer_es=excluded.discount_offer_es, type=excluded.type;

commit;
