-- ============================================================
-- Atlan Metro Green Book — schema + RLS  (generated by build-sql.mjs)
-- ============================================================

create extension if not exists "pgcrypto";

create table if not exists cities (
  id            text primary key,
  name_en       text not null,
  name_ar       text default '',
  name_es       text default '',
  country       text default '',
  center_lat    double precision not null,
  center_lng    double precision not null,
  default_zoom  int default 11,
  source        text default 'seed',
  is_active     boolean default true,
  created_at    timestamptz default now()
);

create table if not exists locations (
  id                uuid primary key default gen_random_uuid(),
  city_id           text not null references cities(id) on delete cascade,
  type              text not null,
  name_en           text not null,
  name_ar           text default '',
  name_es           text default '',
  address           text default '',
  lat               double precision not null,
  lng               double precision not null,
  phone             text default '',
  hours_en          text default '',
  hours_ar          text default '',
  hours_es          text default '',
  halal_certified   boolean default false,
  alcohol_free      boolean default false,
  prayer_space      boolean default false,
  family_friendly   boolean default true,
  worldcup_special  boolean default false,
  discount_code     text,
  discount_offer_en text default '',
  discount_offer_ar text default '',
  discount_offer_es text default '',
  image_url         text default '',
  claimed_by        uuid references auth.users(id),
  source            text default 'seed',
  osm_id            text unique,
  created_at        timestamptz default now(),
  updated_at        timestamptz default now()
);

create table if not exists businesses (
  uid                 uuid primary key references auth.users(id) on delete cascade,
  email               text,
  claimed_location_id uuid references locations(id),
  created_at          timestamptz default now()
);

create index if not exists locations_city_idx on locations (city_id);
create index if not exists locations_type_idx on locations (type);

-- ---------- Row-Level Security ----------
alter table cities     enable row level security;
alter table locations  enable row level security;
alter table businesses enable row level security;

drop policy if exists "public read cities"    on cities;
drop policy if exists "public read locations"  on locations;
drop policy if exists "owner updates location" on locations;
drop policy if exists "owner manages business" on businesses;

create policy "public read cities"    on cities    for select using (true);
create policy "public read locations" on locations for select using (true);
create policy "owner updates location" on locations
  for update using (auth.uid() = claimed_by) with check (auth.uid() = claimed_by);
create policy "owner manages business" on businesses
  for all using (auth.uid() = uid) with check (auth.uid() = uid);

-- ---------- Seed data ----------

insert into cities (id, name_en, name_ar, name_es, country, center_lat, center_lng, default_zoom, source)
values ('atlanta', 'Atlanta', NULL, NULL, 'United States', 33.7544657, -84.3898151, 11, 'osm-onboarded')
on conflict (id) do update set
  name_en = excluded.name_en, center_lat = excluded.center_lat,
  center_lng = excluded.center_lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', 'Atlanta Masjid of Al Islam', NULL, NULL, NULL, 33.738643, -84.310752, NULL, NULL, NULL, NULL, false, true, true, true, false, NULL, NULL, NULL, NULL, 'osm', 'node/462897271')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', '5 Points Islamic Center (Masjid Jami Islamic Center)', NULL, NULL, '105 Broad Street Southwest, Atlanta, GA, 30303', 33.751802, -84.393494, '+14046589124', NULL, NULL, NULL, false, true, true, true, false, NULL, NULL, NULL, NULL, 'osm', 'node/3503081325')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', 'Southeast Islamic Center', NULL, NULL, NULL, 34.090149, -84.291207, NULL, NULL, NULL, NULL, false, true, true, true, false, NULL, NULL, NULL, NULL, 'osm', 'node/12695360106')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', 'Faizan-e-Madinah', NULL, NULL, NULL, 33.904122, -84.155127, NULL, NULL, NULL, NULL, false, true, true, true, false, NULL, NULL, NULL, NULL, 'osm', 'node/13042107552')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', 'Ismaili Jamat Khana', NULL, NULL, 'Carriage Place Court, Scottdale, GA, 30033', 33.797402, -84.278361, NULL, NULL, NULL, NULL, false, true, true, true, false, NULL, NULL, NULL, NULL, 'osm', 'way/51291649')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', 'Al-Farooq Masjid of Atlanta', NULL, NULL, '442 14th Street Northwest, Atlanta, 30318-7944', 33.785832, -84.401542, '+14048747521', NULL, NULL, NULL, false, true, true, true, false, NULL, NULL, NULL, NULL, 'osm', 'way/269845515')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', 'Masjid Al-Mu''minun', NULL, NULL, '1127 Hank Aaron Drive Southwest, Atlanta, GA, 30315', 33.723677, -84.388484, NULL, NULL, NULL, NULL, false, true, true, true, false, NULL, NULL, NULL, NULL, 'osm', 'way/272293462')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', 'Masjid Al-Quran', NULL, NULL, '500 McDonough Boulevard Southeast, Atlanta, 30315', 33.714205, -84.37179, NULL, NULL, NULL, NULL, false, true, true, true, false, NULL, NULL, NULL, NULL, 'osm', 'way/272388688')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', 'Zainabia Islamic Center', NULL, NULL, '1100 Hope Road, Atlanta, GA, 30350', 33.98935, -84.350532, NULL, NULL, NULL, NULL, false, true, true, true, false, NULL, NULL, NULL, NULL, 'osm', 'way/344542447')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', 'Community of Bosniaks, Georgia', NULL, NULL, NULL, 33.925529, -83.973503, NULL, NULL, NULL, NULL, false, true, true, true, false, NULL, NULL, NULL, NULL, 'osm', 'way/387624189')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', 'Bait-ul-Ata Mosque', NULL, NULL, '1800 Willow Trail Parkway, Norcross, GA, 30093', 33.931336, -84.166997, NULL, NULL, NULL, NULL, false, true, true, true, false, NULL, NULL, NULL, NULL, 'osm', 'way/891032228')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', 'Masjid Omar Bin Abdul Aziz Mosque', NULL, NULL, '955 Harbins Road, Lilburn, GA, 30047', 33.89909, -84.170046, '+17702798606', NULL, NULL, NULL, false, true, true, true, false, NULL, NULL, NULL, NULL, 'osm', 'way/891091840')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', 'IC-NUR', NULL, NULL, '1073 Lawrenceville Highway, Lawrenceville, GA, 30046', 33.941145, -84.015749, NULL, NULL, NULL, NULL, false, true, true, true, false, NULL, NULL, NULL, NULL, 'osm', 'way/999112170')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'masjid', 'Islamic Center of North Fulton', NULL, NULL, '1265 Rucker Road, Alpharetta', 34.07357, -84.323354, NULL, NULL, NULL, NULL, false, true, true, true, false, NULL, NULL, NULL, NULL, 'osm', 'way/1498343983')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'Mediterranean Grill', NULL, NULL, '985 Monroe Drive Northeast', 33.781261, -84.368317, '+14049171100', 'Mo-Sa 11:00-20:30; Su 11:00-20:00', NULL, NULL, true, false, false, true, false, NULL, NULL, NULL, NULL, 'osm', 'node/1953501533')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'Lahore Grill', NULL, NULL, '1869 Cobb Parkway South, Marietta, GA, 30060', 33.906962, -84.489539, '+16783989868', 'Tu-Th 11:30-15:00,17:00-22:00; Fr 11:30-13:00,15:00-22:00; Sa-Su 11:30-22:00', NULL, NULL, true, false, false, true, false, NULL, NULL, NULL, NULL, 'osm', 'node/3570258882')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'The Beirut', NULL, NULL, NULL, 33.438631, -84.58878, NULL, NULL, NULL, NULL, true, false, false, true, false, NULL, NULL, NULL, NULL, 'osm', 'node/3761856957')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'Kerala Kitchen', NULL, NULL, NULL, 33.90277, -84.005352, NULL, NULL, NULL, NULL, true, false, false, true, false, NULL, NULL, NULL, NULL, 'osm', 'node/9846855258')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'Blue India', NULL, NULL, '933 Peachtree Street Northeast', 33.779627, -84.383863, '+14049635775', 'Mo-Th 11:30-14:30,17:00-22:00; Fr-Sa 11:30-14:30,17:00-23:00; Su 17:00-22:00', NULL, NULL, true, false, false, true, false, NULL, NULL, NULL, NULL, 'osm', 'node/10129258870')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'Marrakech Express', NULL, NULL, NULL, 33.892448, -84.519881, NULL, 'Tu-Th 16:00-20:00; Fr-Su 11:00-20:00', NULL, NULL, true, false, false, true, false, NULL, NULL, NULL, NULL, 'osm', 'node/10677159561')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'Mukhtaro Beef Burger', NULL, NULL, '258 Hunnicutt Street Northwest, Atlanta, GA, 30313', 33.766486, -84.394364, '+14049936625', '24/7', NULL, NULL, false, false, false, true, false, NULL, NULL, NULL, NULL, 'osm', 'node/11750065291')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'Marietta Fusion Pizza', NULL, NULL, '3000 Windy Hill Road Southeast, Marietta, GA, 30067', 33.90478, -84.465506, '+16785402651', 'We-Mo 11:00-01:00', NULL, NULL, true, false, false, true, false, NULL, NULL, NULL, NULL, 'osm', 'node/11899592230')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'Marietta Wings & More', NULL, NULL, '1869 Cobb Parkway South, Marietta, GA, 30060', 33.907353, -84.488932, '+17709553130', 'Mo-Th 10:30-22:00; Fr 10:30-23:00; Sa 11:00-23:00; Su 11:00-22:00', NULL, NULL, true, false, false, true, false, NULL, NULL, NULL, NULL, 'osm', 'node/11905601496')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'Mediterranean Express', NULL, NULL, '3162 Johnson Ferry Road', 34.025549, -84.423418, NULL, 'Mo-Sa 11:30-20:00; Su 12:00-19:00', NULL, NULL, true, false, false, true, false, NULL, NULL, NULL, NULL, 'osm', 'node/12292410777')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'Shah''s Halal Food', NULL, NULL, '2821 Chastain Meadows Parkway Northwest', 34.02093, -84.556053, NULL, NULL, NULL, NULL, true, false, false, true, false, NULL, NULL, NULL, NULL, 'osm', 'node/12308471949')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'WowBooza', NULL, NULL, '1630 Pleasant Hill Road, Duluth, GA, 30096', 33.946074, -84.123384, '+17707014215', NULL, NULL, NULL, true, false, false, true, false, NULL, NULL, NULL, NULL, 'osm', 'node/12599792714')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'Divan Restaurant & Bar', NULL, NULL, '87 15th Street Northeast', 33.788198, -84.384742, '+16787323989', 'Mo-Th,Su 17:00-24:00; Fr-Sa 17:00-01:00', NULL, NULL, false, false, false, true, false, NULL, NULL, NULL, NULL, 'osm', 'node/12924935614')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'Halal Pizza', NULL, NULL, NULL, 33.787217, -84.2362, NULL, NULL, NULL, NULL, true, false, false, true, false, NULL, NULL, NULL, NULL, 'osm', 'node/13055317410')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'Mediterranean Bistro', NULL, NULL, '3940 Cherokee Street Northwest', 34.049579, -84.596499, '+17704291999', 'Mo-Sa 11:00-20:00', NULL, NULL, true, false, false, true, false, NULL, NULL, NULL, NULL, 'osm', 'node/13269270955')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'Flames Indian Grill', NULL, NULL, '3000 Windy Hill Road Southeast', 33.904698, -84.465546, '+14703080254', '11:00-01:00', NULL, NULL, true, false, false, true, false, NULL, NULL, NULL, NULL, 'osm', 'node/13525279760')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'K Wings Cafe', NULL, NULL, '646 Indian Trail-Lilburn Rd NW, Lilburn, GA, 30047', 33.901014, -84.146686, '+17709312355', 'Mo-Th 11:00-22:00, Fr-Sa 11:00-23:00, Su 12:00-21:00', NULL, NULL, true, false, false, true, false, NULL, NULL, NULL, NULL, 'osm', 'node/13670561537')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'Star Pizza', NULL, NULL, '1000 Marietta Highway, Roswell, GA, 30075', 34.005297, -84.390844, '+17706506717', 'Mo-Sa 11:00-21:30; Su 11:30-21:30', NULL, NULL, true, false, false, true, false, NULL, NULL, NULL, NULL, 'osm', 'node/13827655633')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'Baraka Shawarma Mediterranean Cuisine', NULL, NULL, '68 Walton Street', 33.756456, -84.391064, '+14042309232', '11:00-22:00', NULL, NULL, true, false, false, true, false, NULL, NULL, NULL, NULL, 'osm', 'node/13841900997')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'Cherokee Chophouse', NULL, NULL, '2710 Canton Road, GA, 30066', 34.017129, -84.526715, '+17704270490', 'Mo off; Tu-Th 16:00-22:00; Fr-Su 16:00-23:00', NULL, NULL, true, false, false, true, false, NULL, NULL, NULL, NULL, 'osm', 'way/270268075')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'restaurant', 'ZamZam Halal Supermarket & Restaurant', NULL, NULL, '5432 Buford Highway, Doraville, GA, 30340', 33.900562, -84.277683, NULL, NULL, NULL, NULL, true, false, false, true, false, NULL, NULL, NULL, NULL, 'osm', 'way/422878961')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'grocery', 'Tripoli Halal Meat', NULL, NULL, '585 Franklin Gateway Southeast, Marietta, GA, 30067', 33.938553, -84.506675, '+16789969990', 'Tu-Sa 10:00-20:00; Su 10:00-19:00', NULL, NULL, true, false, false, true, false, NULL, NULL, NULL, NULL, 'osm', 'node/7387142116')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'grocery', 'Bismillah Halal Meat & Grocery', NULL, NULL, '279 Powers Ferry Road Southeast, Marietta, GA, 30067', 33.945034, -84.497739, '+17705658859', 'Mo-Su 10:00-21:00', NULL, NULL, true, false, false, true, false, NULL, NULL, NULL, NULL, 'osm', 'node/10731872211')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'grocery', 'Madina Halal Supermarket', NULL, NULL, '2543 Bells Ferry Road Northeast', 34.013326, -84.550043, NULL, NULL, NULL, NULL, true, false, false, true, false, NULL, NULL, NULL, NULL, 'osm', 'node/13406444411')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
insert into locations (city_id, type, name_en, name_ar, name_es, address, lat, lng, phone, hours_en, hours_ar, hours_es, halal_certified, alcohol_free, prayer_space, family_friendly, worldcup_special, discount_code, discount_offer_en, discount_offer_ar, discount_offer_es, source, osm_id) values ('atlanta', 'grocery', 'Al-Amin', NULL, NULL, NULL, 33.901393, -84.276555, NULL, NULL, NULL, NULL, true, false, false, true, false, NULL, NULL, NULL, NULL, 'osm', 'way/1458488599')
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;
