#!/usr/bin/env node
// Build a single SQL migration from src/data/cities/*.json:
//   - schema (cities, locations, businesses)
//   - Row-Level Security policies
//   - seed INSERTs (idempotent upserts on osm_id / id)
//
// Usage: node scripts/build-sql.mjs > supabase/seed.sql

import { readFile, readdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const CITIES_DIR = join(ROOT, 'src', 'data', 'cities');

const q = (v) => {
  if (v === null || v === undefined || v === '') return 'NULL';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'number') return String(v);
  return `'${String(v).replace(/'/g, "''")}'`;
};

const SCHEMA = `-- ============================================================
-- Atlan Metro Green Book — schema + RLS  (generated by build-sql.mjs)
-- ============================================================

create extension if not exists "pgcrypto";

create table if not exists cities (
  id            text primary key,
  name_en       text not null,
  name_ar       text default '',
  name_es       text default '',
  country       text default '',
  center_lat    double precision not null,
  center_lng    double precision not null,
  default_zoom  int default 11,
  source        text default 'seed',
  is_active     boolean default true,
  created_at    timestamptz default now()
);

create table if not exists locations (
  id                uuid primary key default gen_random_uuid(),
  city_id           text not null references cities(id) on delete cascade,
  type              text not null,
  name_en           text not null,
  name_ar           text default '',
  name_es           text default '',
  address           text default '',
  lat               double precision not null,
  lng               double precision not null,
  phone             text default '',
  hours_en          text default '',
  hours_ar          text default '',
  hours_es          text default '',
  halal_certified   boolean default false,
  alcohol_free      boolean default false,
  prayer_space      boolean default false,
  family_friendly   boolean default true,
  worldcup_special  boolean default false,
  discount_code     text,
  discount_offer_en text default '',
  discount_offer_ar text default '',
  discount_offer_es text default '',
  image_url         text default '',
  claimed_by        uuid references auth.users(id),
  source            text default 'seed',
  osm_id            text unique,
  created_at        timestamptz default now(),
  updated_at        timestamptz default now()
);

create table if not exists businesses (
  uid                 uuid primary key references auth.users(id) on delete cascade,
  email               text,
  claimed_location_id uuid references locations(id),
  created_at          timestamptz default now()
);

create index if not exists locations_city_idx on locations (city_id);
create index if not exists locations_type_idx on locations (type);

-- ---------- Row-Level Security ----------
alter table cities     enable row level security;
alter table locations  enable row level security;
alter table businesses enable row level security;

drop policy if exists "public read cities"    on cities;
drop policy if exists "public read locations"  on locations;
drop policy if exists "owner updates location" on locations;
drop policy if exists "owner manages business" on businesses;

create policy "public read cities"    on cities    for select using (true);
create policy "public read locations" on locations for select using (true);
create policy "owner updates location" on locations
  for update using (auth.uid() = claimed_by) with check (auth.uid() = claimed_by);
create policy "owner manages business" on businesses
  for all using (auth.uid() = uid) with check (auth.uid() = uid);
`;

async function main() {
  const files = (await readdir(CITIES_DIR)).filter((f) => f.endsWith('.json'));
  let sql = SCHEMA + '\n-- ---------- Seed data ----------\n';

  for (const file of files) {
    const payload = JSON.parse(await readFile(join(CITIES_DIR, file), 'utf8'));
    const c = payload.city;

    sql += `\ninsert into cities (id, name_en, name_ar, name_es, country, center_lat, center_lng, default_zoom, source)
values (${q(c.id)}, ${q(c.name_en)}, ${q(c.name_ar)}, ${q(c.name_es)}, ${q(c.country)}, ${q(c.center_lat)}, ${q(c.center_lng)}, ${q(c.default_zoom || 11)}, ${q(c.source || 'seed')})
on conflict (id) do update set
  name_en = excluded.name_en, center_lat = excluded.center_lat,
  center_lng = excluded.center_lng;\n`;

    for (const r of payload.locations) {
      const cols = [
        'city_id', 'type', 'name_en', 'name_ar', 'name_es', 'address',
        'lat', 'lng', 'phone', 'hours_en', 'hours_ar', 'hours_es',
        'halal_certified', 'alcohol_free', 'prayer_space', 'family_friendly',
        'worldcup_special', 'discount_code', 'discount_offer_en',
        'discount_offer_ar', 'discount_offer_es', 'source', 'osm_id',
      ];
      const vals = [
        c.id, r.type, r.name_en, r.name_ar, r.name_es, r.address,
        r.lat, r.lng, r.phone, r.hours_en, r.hours_ar, r.hours_es,
        r.halal_certified, r.alcohol_free, r.prayer_space, r.family_friendly,
        r.worldcup_special, r.discount_code, r.discount_offer_en,
        r.discount_offer_ar, r.discount_offer_es, r.source || 'seed',
        r.osm_id || null,
      ].map(q);

      // Rows with an osm_id upsert on it; hand-seeded rows (no osm_id) insert plainly.
      if (r.osm_id) {
        sql += `insert into locations (${cols.join(', ')}) values (${vals.join(', ')})
on conflict (osm_id) do update set name_en = excluded.name_en, address = excluded.address, lat = excluded.lat, lng = excluded.lng;\n`;
      } else {
        sql += `insert into locations (${cols.join(', ')}) values (${vals.join(', ')});\n`;
      }
    }
  }

  process.stdout.write(sql);
}

main().catch((e) => { console.error(e); process.exit(1); });
